### ISSUE TITLE
Rephrase "data level 3" to "low-level science data products"?

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/open-gamma-ray-astro-gamma2016#6]
Feedback by @kosack on the draft via email:

> One thing is that in the second section (resources) you start talking about DL3 data, which is jargon that has not been introduced at all in the document.  I would use a more common name for that, like "low-level science data products", and then in parentheses write "event-lists, IRFs, and associated technical data". Otherwise, you need to introduce the concept of data levels, etc, which is beyond the scope. 

This would be a big change. If you look at the latest draft ([PDF](https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/blob/master/proceeding/open-gamma-ray-astro-gamma2016.pdf)) you'll see that I mention DL3 in Figure 1 already, and there's now sections called "Data level 3 specifications" and "Data level 4 & 5 specifications".
Since we're using the DL3 term a lot (see https://github.com/open-gamma-ray-astro/2016-04_IACT_DL3_Meeting), and "low-level science data products" isn't a well-defined or widely used term, I'm inclined to go "all in" and stick with the DL3 term in this proceeding.

@kosack - With the latest draft, do you still think I should change everywhere to something like "low-level science data products" (for DL3) and "high-level science data products (for DL4+5)? Or maybe it's OK now as-is or there's smaller changes we could make to define the distinction better?

@cboisson @TarekHC @woodmd - Thoughts?

**Comment by cboisson** [comment]
Christoph,

to shorten the text you can as proposed replace the bullet list in the 
“data level 3 specifications” section by a sentence.

Karl is right in that DL3 is jargon. I should have realized earlier. You 
can as he suggest in the title of the section or the very first time it 
is mentionned in the text add "low-level science data products" 
(event-lists, IRFs, and associated technical data; DL3) or  "high-level 
science data products (images, light curves, maps; DL4+5). This would 
then appear only once and may be in the section title.

Cheers,

Catherine

**Comment by TarekHC** [comment]
Hi all, 

I think before there was a sentence defining DL3 in the introduction that seems to have disappeared. I think it would be ok if we use DL3 everywhere, as long as we properly define it (as Catherine suggests).

**Comment by kosack** [comment]
As long as it is defined before you use it I'm happy! The comment was just because there was no definition before it was used.  The definition of the lower data levels has changed a bit in the last few months (with the new data naming scheme), but generally one could say something like "The data level DLx refers to the amount of processing that has been applied to the data, with DL0-DL2 representing instrument-specific raw and intermediate data products;  common science data products start at DL3 (event lists, IRFs, and associated instrument-specific technical data), and DL4 (images, spectral, lightcurves, and other products derived from DL3).

**Comment by cdeil** [comment]
I've defined the data levels in the introduction: https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/commit/abed9389f3e9c8d485474dc0c2ec243367d48fcd

Somehow I found adding it to the existing paragraphs was difficult, I think it might not be well-structured and -written any more.

I also tried to explain that we use "observation" and OBS_ID at the moment in the DL3 section and I made everything fit on 6 pages.

@kosack @TarekHC @cboisson @saveriolombardi - If you have time to have another look, especially at the second paragraph of the introduction, that would be great.

Comments here, or even better pull requests highly welcome.

Latest draft is here: https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/blob/master/proceeding/open-gamma-ray-astro-gamma2016.pdf

I have to go now, but will submit tonight at 10 pm.

**Comment by cdeil** [comment]
It is what it is (hopefully not too bad).

I fixed one more issue (the axis labels for EDISP where exchanged), tried to improve the figure positioning / page breaks a bit and tagged the final version:
https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/releases/tag/final

I'm submitting it now.
If you find any more mistakes, please _don't_ tell me.
:-)
