### ISSUE TITLE
Submit to ArXiv?

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/open-gamma-ray-astro-gamma2016#8]
@cboisson @TarekHC @woodmd @kosack - Should I post the final version on ArXiv?

I would say yes, so that more people will see it and citing it becomes easier.

It's here: https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/blob/master/proceeding/open-gamma-ray-astro-gamma2016.pdf
and tagged here: https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/releases/tag/final

**Comment by cboisson** [comment]
I would yes.
It is a good time, just before ADASS, to post on ArXiv.

**Comment by cdeil** [comment]
OK, I'm submitting this to ArXiv today.

**Comment by TarekHC** [comment]
Argh, sorry for not giving feedback.

I see no reason not to upload it to arXiv, so upload it indeed.

**Comment by cdeil** [comment]
So ArXiv doesn't allow submitting just the PDF. Outrageous!
At least on astro-ph I should be able to submit my paper in FITS format then.
After all, it's the gold standard arxiv format for astronomy.

**Comment by cdeil** [comment]
I've made a tarball of the LaTeX files (see 732f89c ) and the processing on the ArXiv server says it's OK. But the output PDF is missing the References on the last page (otherwise it's OK).

LaTeX build log from them is here:
https://gist.github.com/cdeil/d6058e6885b90cb125a74b52b7c73aca

Could someone that knows LaTeX please have a look, or try this and see if the references appear for you on page 6?

```
mkdir test123
cd test123
wget https://github.com/open-gamma-ray-astro/open-gamma-ray-astro-gamma2016/raw/master/proceeding/open-gamma-ray-astro-gamma2016.tar.gz
tar zxvf open-gamma-ray-astro-gamma2016.tar.gz
make
open open-gamma-ray-astro-gamma2016.pdf 
```

**Comment by kosack** [comment]
you can also try `latexmk` which replaces the custom makefile and should process all latex docs correctly. No idea what arxive uses.

`latexmk -pdf open-gamma-ray-astro-gamma2016`

**Comment by TarekHC** [comment]
At least in my laptop (Ubuntu 14.04), the test you provided does generate the references properly.

**Comment by cdeil** [comment]
Found this: https://arxiv.org/help/submit_tex#bibtex
They don't run bibtex.
Re-trying now.

**Comment by cdeil** [comment]
It worked, the PDF looks OK now on ArXiv.
Have to go, but I'll finish the submission later.

**Comment by cdeil** [comment]
Submitted. Should appear on ArXiv tomorrow.

**Comment by cdeil** [comment]
Looks OK to me: https://arxiv.org/abs/1610.01884
